Meteor.subscribe("cpanel_exchange")
Meteor.subscribe('rice_staff')
Meteor.subscribe('rice_userStaff')
Meteor.subscribe('rice_saleItemsCategories')
Meteor.subscribe('rice_saleCategories')
Meteor.subscribe('rice_unit')
Meteor.subscribe('rice_purchaseCategories')
Meteor.subscribe('rice_purchaseItems') 
